### ISSUE TITLE
Changes to `split_out` defaults may lead to P2P errors when mixing distributed client with single-machine client

### ISSUE THREAD

**Issue by hendrikmakait** [dask-contrib/dask-expr#955]
```python
import numpy as np
import pandas as pd
import dask.dataframe as dd
from distributed import Client

if __name__ == "__main__":
    with Client(set_as_default=True) as client:
        df = pd.DataFrame(
        {"x": np.random.random(1000), "y": np.random.random(1000)},
        index=np.arange(1000),
    )
        ddf = dd.from_pandas(df, npartitions=10)
        ddf =ddf.drop_duplicates()
        ddf.compute(scheduler="sync")
```
fails with 
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/shuffle/_core.py", line 388, in get_worker_plugin
    worker = get_worker()
             ^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/worker.py", line 2728, in get_worker
    raise ValueError("No worker found") from None
ValueError: No worker found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/shuffle/_core.py", line 494, in handle_transfer_errors
    yield
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/shuffle/_shuffle.py", line 79, in shuffle_transfer
    return get_worker_plugin().add_partition(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/shuffle/_core.py", line 390, in get_worker_plugin
    raise RuntimeError(
RuntimeError: `shuffle='p2p'` requires Dask's distributed scheduler. This task is not running on a Worker; please confirm that you've created a distributed Client and are submitting this computation through it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/hendrikmakait/projects/dask/dask-expr/foo.py", line 14, in <module>
    ddf.compute(scheduler="sync")
  File "/Users/hendrikmakait/projects/dask/dask-expr/dask_expr/_collection.py", line 451, in compute
    return DaskMethodsMixin.compute(out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/dask/base.py", line 375, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/dask/base.py", line 661, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/shuffle/_shuffle.py", line 78, in shuffle_transfer
    with handle_transfer_errors(id):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/distributed/shuffle/_core.py", line 498, in handle_transfer_errors
    raise RuntimeError(f"P2P shuffling {id} failed during transfer phase") from e
RuntimeError: P2P shuffling 4645ae1fc52bfdbb0ab67619963f80aa failed during transfer phase
```

The problem is that `split_out` defaults to `1` with legacy `dask.dataframe`, but may default to `>1` and thus inject a shuffle for `dask-expr`.

Given that we already raise a warning against mixing distributed and single-machine schedulers, I'm inclined not to act on this. 
```
/opt/homebrew/Caskroom/mambaforge/base/envs/dask-expr/lib/python3.12/site-packages/dask/base.py:1462: UserWarning: Running on a single-machine scheduler when a distributed client is active might lead to unexpected results.
```

**Comment by hendrikmakait** [comment]
Closing this as not planned for now, feel free to comment/reopen if you encounter this issue.
